[package]
name = "test-suite"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]


[features]
# use library feature to disable all instantiate/execute/query exports
library = []
default = []
vanilla = []


[dependencies]
btsg-nft-scripts            = { workspace = true }
bs721                       = { workspace = true }
btsg-auth                   = { workspace = true}
btsg-wavs                   = { workspace = true}
bs721-base                  = { workspace = true }
bs721-factory               = { workspace = true }
bs721-curve                 = { workspace = true }
bs721-royalties             = { workspace = true }
bs721-launchparty           = { workspace = true }

anyhow           = { workspace = true }
cosmwasm-schema  = { workspace = true }
cosmwasm-std     = { workspace = true }
cw2              = { workspace = true }
cw-orch          = { version = "0.28.0", features = ["daemon"] }
cw-storage-plus  = { workspace = true }
cw-utils         = { version = "1.0.3" }
hex              = { version = "0.4.3" }
schemars         = { workspace = true }
serde            = { workspace = true }
 

[dev-dependencies]
rand = "0.8.5"
cw-multi-test = { git = "https://github.com/permissionlessweb/cw-multi-test", branch = "mvp" }
# abstract-cw-multi-test = { version = "2.2.4" }

