[package]
name          = "bs721-launchparty"
description   = "A basic launchpad contract for Bs721 NFTs."
authors       = [
  "Angelo Recca <angelorc@users.noreply.github.com>",
]
version       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []
interface = ["dep:cw-orch"]

[dependencies]
cosmwasm-schema         = { workspace = true }
cosmwasm-std            = { workspace = true }
cw-utils                = { workspace = true }
cw2                     = { workspace = true }
bs721-base              = { workspace = true, features = ["library"] }
bs721                   = { workspace = true }
bs721-royalties         = { workspace = true, features = ["library"] }
cw-storage-plus         = { workspace = true }
schemars                = { workspace = true }
serde                   = { workspace = true }
thiserror               = { workspace = true }
cosmos-sdk-proto        = { workspace = true }
cw-orch                 = { version = "0.28.0", optional = true }

[dev-dependencies]
anyhow           = { version = "1" }
cw-multi-test    = { workspace = true }
derivative       = { version = "2.2" }
easy-addr        = { workspace = true }
prost            = { version = "0.11.9" }