[package]
name = "btsg-nft-scripts"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/DA0-DA0/dao-contracts"
version.workspace = true

[dependencies]
bs721                      = { path = "../packages/bs721"}
bs721-base                 = { path = "../contracts/collections/bs721-base"  }
bs721-launchparty         = { path = "../contracts/minters/bs721-launchparty"  }
btsg-wavs                 = { path = "../contracts/smart-accounts/btsg-wavs"   }
btsg-auth                 = { path = "../packages/btsg-auth"  }
cosmwasm-std.workspace     = true

clap = { version = "4.0.32", features = ["derive"] }
cw-orch-polytone = { package = "abstract-cw-orch-polytone", version = "4.0.0" }
cw-orch-interchain = { version = "0.9.0",  features = ["daemon"] }
cw-orch-interchain-core = "0.10.0"
cw-orch   = { version = "0.26.0", features = ["daemon"] }
dirs = "5.0.1"

env_logger = "0.10.0"
log = "0.4.22"
dotenv                     = { version = "0.15.0" }
anyhow = "1"
pretty_env_logger          = { version = "0.5.0" }
serde                        = { version = "1.0.140", default-features = false, features = ["derive"] }
serde_json = "1.0.79"

reqwest = { version = "0.11.9" }

# crypto libraries
base64-serde = "0.8.0"
base64 = "0.22.0"

[dev-dependencies]
tokio = "1.39.3"

# Cargo CLI commands
[[bin]]
name = "connect-ibc"
path = "src/bin/connect_ibc.rs"
[[bin]]
name = "create-remote-account"
path = "src/bin/create_remote_account.rs"
[[bin]]
name = "deploy-ibc"
path = "src/bin/deploy_ibc.rs"
[[bin]]
name = "deploy-modules"
path = "src/bin/deploy_modules.rs"
[[bin]]
name = "full-deploy"
path = "src/bin/full_deploy.rs"
 
[[bin]]
name = "manual-deploy"
path = "src/bin/manual_deploy.rs"
[[bin]]
name = "migrate"
path = "src/bin/migrate.rs"
[[bin]]
name = "create-nft-account"
path = "src/bin/create_nft_account.rs"