/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { PartyType, Uint128, Timestamp, Uint64, InstantiateMsg, Coin, ExecuteMsg, QueryMsg, Addr, Config, MaxPerAddressResponse } from "./Bs721Launchparty.types";
export interface Bs721LaunchpartyMessage {
  contractAddress: string;
  sender: string;
  mint: ({
    amount,
    referral
  }: {
    amount: number;
    referral?: string;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
  setNftAddress: ({
    nftAddr
  }: {
    nftAddr: string;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class Bs721LaunchpartyMessageComposer implements Bs721LaunchpartyMessage {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.mint = this.mint.bind(this);
    this.setNftAddress = this.setNftAddress.bind(this);
  }

  mint = ({
    amount,
    referral
  }: {
    amount: number;
    referral?: string;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          mint: {
            amount,
            referral
          }
        })),
        funds
      })
    };
  };
  setNftAddress = ({
    nftAddr
  }: {
    nftAddr: string;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_nft_address: {
            nft_addr: nftAddr
          }
        })),
        funds
      })
    };
  };
}