/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Uint128, InstantiateMsg, Coin, ExecuteMsg, PartyType, Timestamp, Uint64, MsgCreateLaunchparty, ContributorMsg, MsgCreateCurve, QueryMsg, Addr, Config } from "./Bs721Factory.types";
export interface Bs721FactoryMessage {
  contractAddress: string;
  sender: string;
  updateConfig: ({
    bs721CodeId,
    bs721CurveCodeId,
    bs721LaunchpartyCodeId,
    bs721RoyaltiesCodeId,
    createNftSaleFee,
    owner,
    protocolFeeBps
  }: {
    bs721CodeId?: number;
    bs721CurveCodeId?: number;
    bs721LaunchpartyCodeId?: number;
    bs721RoyaltiesCodeId?: number;
    createNftSaleFee?: Coin;
    owner?: string;
    protocolFeeBps?: number;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
  createLaunchaparty: ({
    contributors,
    maxPerAddress,
    name,
    partyType,
    paymentAddress,
    price,
    referralFeeBps,
    sellerFeeBps,
    startTime,
    symbol,
    uri
  }: {
    contributors: ContributorMsg[];
    maxPerAddress?: number;
    name: string;
    partyType: PartyType;
    paymentAddress: string;
    price: Coin;
    referralFeeBps: number;
    sellerFeeBps: number;
    startTime: Timestamp;
    symbol: string;
    uri: string;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
  createCurve: ({
    maxEdition,
    maxPerAddress,
    name,
    paymentAddress,
    paymentDenom,
    ratio,
    referralFeeBps,
    sellerFeeBps,
    startTime,
    symbol,
    uri
  }: {
    maxEdition?: number;
    maxPerAddress?: number;
    name: string;
    paymentAddress: string;
    paymentDenom: string;
    ratio: number;
    referralFeeBps: number;
    sellerFeeBps: number;
    startTime: Timestamp;
    symbol: string;
    uri: string;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
  createRoyaltiesGroup: ({
    contributors,
    denom
  }: {
    contributors: ContributorMsg[];
    denom: string;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class Bs721FactoryMessageComposer implements Bs721FactoryMessage {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateConfig = this.updateConfig.bind(this);
    this.createLaunchaparty = this.createLaunchaparty.bind(this);
    this.createCurve = this.createCurve.bind(this);
    this.createRoyaltiesGroup = this.createRoyaltiesGroup.bind(this);
  }

  updateConfig = ({
    bs721CodeId,
    bs721CurveCodeId,
    bs721LaunchpartyCodeId,
    bs721RoyaltiesCodeId,
    createNftSaleFee,
    owner,
    protocolFeeBps
  }: {
    bs721CodeId?: number;
    bs721CurveCodeId?: number;
    bs721LaunchpartyCodeId?: number;
    bs721RoyaltiesCodeId?: number;
    createNftSaleFee?: Coin;
    owner?: string;
    protocolFeeBps?: number;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_config: {
            bs721_code_id: bs721CodeId,
            bs721_curve_code_id: bs721CurveCodeId,
            bs721_launchparty_code_id: bs721LaunchpartyCodeId,
            bs721_royalties_code_id: bs721RoyaltiesCodeId,
            create_nft_sale_fee: createNftSaleFee,
            owner,
            protocol_fee_bps: protocolFeeBps
          }
        })),
        funds
      })
    };
  };
  createLaunchaparty = ({
    contributors,
    maxPerAddress,
    name,
    partyType,
    paymentAddress,
    price,
    referralFeeBps,
    sellerFeeBps,
    startTime,
    symbol,
    uri
  }: {
    contributors: ContributorMsg[];
    maxPerAddress?: number;
    name: string;
    partyType: PartyType;
    paymentAddress: string;
    price: Coin;
    referralFeeBps: number;
    sellerFeeBps: number;
    startTime: Timestamp;
    symbol: string;
    uri: string;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_launchaparty: {
            contributors,
            max_per_address: maxPerAddress,
            name,
            party_type: partyType,
            payment_address: paymentAddress,
            price,
            referral_fee_bps: referralFeeBps,
            seller_fee_bps: sellerFeeBps,
            start_time: startTime,
            symbol,
            uri
          }
        })),
        funds
      })
    };
  };
  createCurve = ({
    maxEdition,
    maxPerAddress,
    name,
    paymentAddress,
    paymentDenom,
    ratio,
    referralFeeBps,
    sellerFeeBps,
    startTime,
    symbol,
    uri
  }: {
    maxEdition?: number;
    maxPerAddress?: number;
    name: string;
    paymentAddress: string;
    paymentDenom: string;
    ratio: number;
    referralFeeBps: number;
    sellerFeeBps: number;
    startTime: Timestamp;
    symbol: string;
    uri: string;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_curve: {
            max_edition: maxEdition,
            max_per_address: maxPerAddress,
            name,
            payment_address: paymentAddress,
            payment_denom: paymentDenom,
            ratio,
            referral_fee_bps: referralFeeBps,
            seller_fee_bps: sellerFeeBps,
            start_time: startTime,
            symbol,
            uri
          }
        })),
        funds
      })
    };
  };
  createRoyaltiesGroup = ({
    contributors,
    denom
  }: {
    contributors: ContributorMsg[];
    denom: string;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_royalties_group: {
            contributors,
            denom
          }
        })),
        funds
      })
    };
  };
}