/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Timestamp, Uint64, InstantiateMsg, ExecuteMsg, QueryMsg, Uint128, PriceResponse, Addr, Config, MaxPerAddressResponse } from "./Bs721Curve.types";
export interface Bs721CurveMessage {
  contractAddress: string;
  sender: string;
  mint: ({
    amount,
    referral
  }: {
    amount: number;
    referral?: string;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
  burn: ({
    minOutAmount,
    referral,
    tokenIds
  }: {
    minOutAmount: number;
    referral?: string;
    tokenIds: number[];
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class Bs721CurveMessageComposer implements Bs721CurveMessage {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.mint = this.mint.bind(this);
    this.burn = this.burn.bind(this);
  }

  mint = ({
    amount,
    referral
  }: {
    amount: number;
    referral?: string;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          mint: {
            amount,
            referral
          }
        })),
        funds
      })
    };
  };
  burn = ({
    minOutAmount,
    referral,
    tokenIds
  }: {
    minOutAmount: number;
    referral?: string;
    tokenIds: number[];
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          burn: {
            min_out_amount: minOutAmount,
            referral,
            token_ids: tokenIds
          }
        })),
        funds
      })
    };
  };
}