/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.25.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Bs721Base.types";
import * as _1 from "./Bs721Base.client";
import * as _2 from "./Bs721Base.message-composer";
import * as _3 from "./Bs721Curve.types";
import * as _4 from "./Bs721Curve.client";
import * as _5 from "./Bs721Curve.message-composer";
import * as _6 from "./Bs721Royalties.types";
import * as _7 from "./Bs721Royalties.client";
import * as _8 from "./Bs721Royalties.message-composer";
import * as _9 from "./Bs721Factory.types";
import * as _10 from "./Bs721Factory.client";
import * as _11 from "./Bs721Factory.message-composer";
import * as _12 from "./Bs721Launchparty.types";
import * as _13 from "./Bs721Launchparty.client";
import * as _14 from "./Bs721Launchparty.message-composer";
export namespace contracts {
  export const Bs721Base = { ..._0,
    ..._1,
    ..._2
  };
  export const Bs721Curve = { ..._3,
    ..._4,
    ..._5
  };
  export const Bs721Royalties = { ..._6,
    ..._7,
    ..._8
  };
  export const Bs721Factory = { ..._9,
    ..._10,
    ..._11
  };
  export const Bs721Launchparty = { ..._12,
    ..._13,
    ..._14
  };
}